/* LinkedIn profile source of truth (English, verbatim where available) */
const LINKEDIN_EN = {
  headline:
    "Partner Program Manager @ ByteDance | Trust & Safety · Partner Programs · Platform/Search/AI-Data Support (APAC & Global)",
  role: "Partner Program Manager TRUST&SAFETY",
  company: "ByteDance",
  location: "Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia",
  about:
    "Partner Program Manager with 8+ years of experience in building and governing large-scale partner programs and operations. Total experience: 10 years and 2 months.",
  totalExperience: "10 years and 2 months",
  languages: [
    "Korean — Native or bilingual proficiency",
    "English — Full professional proficiency",
  ],
  education: [
    {
      school: "Kyungpook National University",
      degree: "Bachelor's degree, Automotive Engineering Technology/Technician",
      period: "2007 — 2015",
      location: "South Korea",
    },
    {
      school: "University of the Visayas",
      degree: "Language course, ENGLISH LANGUAGE AND LITERATURE/LETTERS, Course certificate",
      period: "2012",
      location: "Cebu, Philippines",
    },
  ],
  courses: [
    "Data Quality project",
    "Design of experiments in Six Sigma",
    "FMEA and Design for Six Sigma",
    "Operation management of Quality",
    "Organizational Goals and Six Sigma",
    "Six Sigma Metrix",
    "Six Sigma performance Metrix",
    "Six Sigma project identification",
  ],
  skills: [
    "ensuring compliance", "managed staffing", "performance data", "coaching",
    "project performance", "communication", "operations manager", "technical skills",
    "web development", "media", "management", "development", "partner program",
    "operational excellence", "emergency response", "documenting", "large-scale scrum (less)",
    "collaboration", "program manager", "customer inquiries", "production schedules",
    "exceptional customer service", "talent management", "general troubleshooting",
    "compliance education", "improving operations", "driving performance", "bpo",
    "production scheduling", "business operations", "staffing", "manufacturing execution system",
    "content creation", "human resources", "project management", "web platform",
    "market analysis", "partner operations", "cross-functional teams",
    "content review", "social media", "program management", "reports", "budgeting",
    "production lines", "training", "leadership", "mental health", "onboarding",
    "ai (artificial intelligence)", "site performance", "operational strategies",
    "process improvement", "strategic initiatives", "performance management",
    "troubleshooting", "service delivery", "vendor management", "cost management",
    "quality control", "crisis management", "wellness programs", "kpi", "kpis",
    "technical support", "regulatory affairs", "reporting", "financial management",
    "financial tracking", "customer service", "outsourcing", "wellness",
    "executive leadership", "manufacturing execution system (mes)",
  ],
  certifications: [
    { name: "Getting started with Google Workspace (Google)", issuer: "Coursera", issued: "Jun 2021" },
    { name: "Google Cloud Digital Leader Training (Google)", issuer: "Coursera", issued: "Jun 2021" },
    { name: "Introduction to Social Media Marketing", issuer: "Coursera", issued: "Jun 2021" },
    { name: "Getting Started with Azure", issuer: "Coursera", issued: "Jun 2021" },
    { name: "Google Project Management (Google)", issuer: "Coursera", issued: "Jun 2021" },
    { name: "Advanced Google Analytics", issuer: "Google Digital Academy (Skillshop)", issued: "Feb 2020", expires: "Feb 2023" },
    { name: "Google Analytics for Beginners", issuer: "Google Digital Academy (Skillshop)", issued: "Feb 2020", expires: "Feb 2023" },
    { name: "Google Tag Manager Fundamentals", issuer: "Google Digital Academy (Skillshop)", issued: "Feb 2020", expires: "Feb 2023" },
    { name: "Google Ads Search Qualification", issuer: "Google Digital Academy (Skillshop)", issued: "Jun 2021", expires: "Jun 2022" },
    { name: "Google Analytics Individual Qualification", issuer: "Google Digital Academy (Skillshop)", issued: "Jun 2021", expires: "Jun 2022" },
  ],
  experience: [
    {
      date: "Mar 2023 — Present",
      title: "Partner Program Manager TRUST&SAFETY",
      org: "ByteDance · Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia",
      highlights: [
        "Crisis Management: Led emergency response to prevent exposure to traumatic content on TikTok, ensuring user mental health and platform integrity.",
        "Wellness Support: Implemented wellness programs and increased access to counseling for BPO content review teams, reducing attrition and absenteeism.",
        "Operational Efficiency: Identified staffing misalignments, recalibrated shifts, and reduced operational costs across multiple BPO sites.",
        "KPI Mitigation: Collaborated with internal teams to minimize the impact of emergency guidelines on KPIs while maintaining quality standards.",
        "High-Performance Teams: Aligned Partner Operations Managers (POMs) with market strengths, improving site rankings and operational success.",
        "Onboarding Excellence: Developed a highly praised onboarding program, boosting team satisfaction and recognition from HR and leadership.",
        "Process Standardization: Standardized communication channels, reporting processes, and performance management frameworks across seven sites, improving cross-team collaboration.",
        "Vendor Management: Strengthened relationships with BPO vendors, enhancing collaboration and ensuring efficient service delivery.",
        "Cultural Integration: Integrated global team members with diverse backgrounds, fostering a collaborative and inclusive work environment.",
        "Cost-Effective Shift Management: Optimized staffing, reduced unnecessary shifts, and improved cost efficiency, while complying with labor laws.",
        "Process Streamlining: Consolidated WBR/MBR sessions, freeing up time for strategic initiatives and improving operational efficiency.",
        "Data-Driven Decisions: Utilized performance data and feedback to refine metrics, improving operations and ensuring alignment with business goals.",
        "Cross-functional Team Management: Led cross-functional teams by aligning strengths, fostering collaboration, and driving performance improvements, ensuring business success and global recognition.",
      ],
    },
    {
      date: "Apr 2022 — Mar 2023",
      title: "Partner Operations Manager",
      org: "ByteDance · Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia",
      highlights: [
        "Program/Project Success: Ensured the success of programs/projects by achieving core KPI goals and driving service delivery excellence.",
        "Operational Excellence: Held partner sites accountable for performance, guiding them toward operational excellence.",
        "Financial Management: Ensured adherence to budget and accurate financial tracking of partner production, training, and related expenses.",
        "Vendor Relationship Management: Built and maintained strong relationships with outsourcing partners, managing vendor performance.",
        "Risk Mitigation: Proactively identified operational and performance risks, implementing mitigations for assigned sites and business lines.",
        "Executive Communication: Articulated site performance and any remediation plans to executive leadership.",
        "Multitasking & Prioritization: Managed multiple responsibilities simultaneously, effectively prioritizing and meeting deadlines.",
        "Continuous Improvement: Focused on operational excellence and process improvement, re-engineering site-level operations (e.g., WFM, floor management).",
        "Stakeholder Management: Managed complex vendor and internal relationships, ensuring adherence to standard operating procedures.",
      ],
    },
    {
      date: "Jan 2019 — Mar 2022",
      title: "Operations Team Lead",
      org: "Webhelp APAC · Kuala Lumpur",
      highlights: [
        "Operations Management: Directed and controlled day-to-day operations, ensuring compliance with company and regulatory standards to deliver high-quality service.",
        "Leadership & Oversight: Led customer service and quality management teams within a defined area to ensure operational excellence.",
        "Strategy Coordination: Developed and coordinated operational strategies to deliver exceptional customer service while meeting regulatory and company requirements.",
        "Talent Development: Provided informal and formal feedback for employee development, identifying and nurturing talent through ongoing performance evaluations.",
        "Staffing & HR Collaboration: Managed staffing levels, collaborating with HR to ensure the right talent was in place.",
        "Succession Planning & Development: Promoted leadership growth through coaching, training, and development to ensure a strong management pipeline.",
        "Communication Leadership: Facilitated strong communication across teams, leading meetings to ensure information was effectively shared and understood.",
        "Performance Management: Implemented corrective actions when performance fell below expectations, adjusting strategies and goals as needed.",
        "Training & Compliance: Ensured employees received the necessary training, including ongoing compliance education to maintain standards.",
      ],
    },
    {
      date: "Jan 2019 — Jun 2019",
      title: "AI Device Technical Support",
      org: "Webhelp APAC · Kuala Lumpur, Kuala Lumpur, Malaysia",
      highlights: [
        "Customer Support: Answered support calls, documenting case details for follow-up.",
        "Technical Assistance: Assisted users with inquiries and technical issues via phone and email.",
        "Escalation Management: Responded to customer escalations, escalating issues to higher support tiers as needed.",
        "Collaboration: Worked with other technicians to resolve issues and properly close help tickets.",
        "Ticket Management: Managed an individual queue of support tickets.",
        "Management Support: Followed management direction and provided feedback on support processes.",
      ],
    },
    {
      date: "Nov 2016 — Nov 2018",
      title: "Business Operations Specialist",
      org: "Accenture · Kuala Lumpur",
      highlights: [
        "Technical Support: Provided technical support for web platform and user-related issues.",
        "Customer Service: Managed customer inquiries and support via SNS channels.",
        "Website Content Management: Responsible for maintaining and updating website content.",
        "Team Support: Assisted senior managers in overseeing a shift team for the Korean market.",
        "Client Communication: Acted as a market representative, addressing operational issues with clients.",
        "Data Analysis & Reporting: Analyzed data to generate reports for project performance evaluation.",
        "Troubleshooting Support: Offered technical and general troubleshooting support through social media channels.",
      ],
    },
    {
      date: "Oct 2015 — Sep 2016",
      title: "Assistant Production Manager",
      org: "Hwaseung R&A · Enterprise, Alabama, United States",
      highlights: [
        "Production Scheduling & Planning: Coordinated production schedules and ensured alignment with quality control standards.",
        "Equipment Maintenance: Monitored and maintained production lines and equipment to ensure continuous operation.",
        "Issue Resolution: Analyzed and resolved operational issues promptly to minimize production downtime.",
        "Daily Shipping: Ensured timely completion of daily shipping requirements.",
        "Production & Quality Targets: Worked to meet daily and weekly production and quality targets based on forecasts.",
        "MES Development & Updates: Led the development and updates of the Manufacturing Execution System (MES) for optimal workflow.",
      ],
    },
  ],
};
