const GITHUB_BASE = "https://github.com/Benjamin5607";

const CATEGORIES = {
  ai: { label: "AI & Agentic Systems", icon: "🧠" },
  global: { label: "Global Culture & Risk", icon: "🌍" },
  games: { label: "Games & Simulations", icon: "🎮" },
  edtech: { label: "Education & Social Impact", icon: "📚" },
  tools: { label: "Developer Tools & Utilities", icon: "🛠️" },
};

const PROJECTS = [
  {
    name: "model_JekyllHyde",
    title: "Jekyll & Hyde Dual-Persona LLM",
    description: "이중 페르소나 LLM 플랫폼. Jekyll/Hyde 듀얼 에이전트 아키텍처로 서로 다른 관점의 AI 페르소나를 구현하고, install package로 배포 가능.",
    stack: ["Python", "LLM", "Dual-Agent"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/model_JekyllHyde`,
  },
  {
    name: "Sereme_Hypatia",
    title: "Sereme Hypatia",
    description: "AI 마인드 컨설팅 플랫폼. TypeScript 기반으로 AI를 활용한 심리·마인드셋 컨설팅 경험을 제공.",
    stack: ["TypeScript", "AI", "Consulting"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/Sereme_Hypatia`,
  },
  {
    name: "zerro_ai_landing",
    title: "Zerro AI OS",
    description: "에이전틱 AI 오케스트레이션 플랫폼 랜딩. Parallel Swarm Engine, Supabase Vector RAG, MCP 통합을 목표로 하는 Zerro AI 생태계의 공식 페이지.",
    stack: ["HTML", "Next.js", "Agentic AI"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/zerro_ai_landing`,
    external: "https://zerroai.space",
  },
  {
    name: "space_manger",
    title: "Space Manager",
    description: "실시간 우주 데이터 기반 게임. ISS 보급 미션과 SpaceX 타이쿤 시뮬레이션을 TypeScript로 구현.",
    stack: ["TypeScript", "Real-time Data", "Simulation"],
    category: "games",
    featured: true,
    url: `${GITHUB_BASE}/space_manger`,
  },
  {
    name: "country_janggi",
    title: "Country Janggi",
    description: "3D 국가 단위 장기 게임. Hunyuan 3D 메시와 한자 기물 라벨로 문화적 정체성을 담은 전략 보드게임.",
    stack: ["TypeScript", "Three.js", "3D"],
    category: "games",
    featured: true,
    url: `${GITHUB_BASE}/country_janggi`,
  },
  {
    name: "global_culture_risk_dashboard",
    title: "Global Culture Risk Dashboard",
    description: "글로벌 문화 리스크를 시각화하는 대시보드. 다문화 환경에서의 문화적 민감도와 리스크 지표를 한눈에 파악.",
    stack: ["HTML", "Data Viz", "Risk Analytics"],
    category: "global",
    featured: true,
    url: `${GITHUB_BASE}/global_culture_risk_dashboard`,
  },
  {
    name: "zerro_coder_test",
    title: "Zerro Coder Test",
    description: "Zerro AI 코딩 에이전트 테스트베드. 에이전트 기반 코드 생성·실행 워크플로우 검증.",
    stack: ["TypeScript", "AI Agent"],
    category: "ai",
    url: `${GITHUB_BASE}/zerro_coder_test`,
  },
  {
    name: "ai_agent_emily",
    title: "AI Agent Emily",
    description: "Emily 페르소나 AI 에이전트. 대화형 AI 어시스턴트 프로토타입.",
    stack: ["Python", "LLM", "Agent"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_emily`,
  },
  {
    name: "ai_agent_mina",
    title: "AI Agent Mina",
    description: "Mina 페르소나 AI 에이전트. 맞춤형 AI 어시스턴트 구현.",
    stack: ["Python", "LLM", "Agent"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_mina`,
  },
  {
    name: "ai_agent_mina_automation",
    title: "AI Agent Mina Automation",
    description: "Mina 에이전트 자동화 확장. 반복 업무 자동화 및 워크플로우 연동.",
    stack: ["Python", "Automation", "Agent"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_mina_automation`,
  },
  {
    name: "AI_Red_Kernel_bot",
    title: "AI Red Kernel Bot",
    description: "Red Kernel 기반 AI 봇. JavaScript로 구현된 대화형 AI 서비스.",
    stack: ["JavaScript", "Bot", "AI"],
    category: "ai",
    url: `${GITHUB_BASE}/AI_Red_Kernel_bot`,
  },
  {
    name: "AI-Sports-Bot",
    title: "AI Sports Bot",
    description: "스포츠 데이터·뉴스 기반 AI 봇. 경기 정보와 분석을 제공하는 Python AI 서비스.",
    stack: ["Python", "Sports", "Bot"],
    category: "ai",
    url: `${GITHUB_BASE}/AI-Sports-Bot`,
  },
  {
    name: "promptsister",
    title: "Prompt Sister",
    description: "프롬프트 생성기. 효과적인 AI 프롬프트를 구조화하고 생성하는 JavaScript 도구.",
    stack: ["JavaScript", "Prompt Engineering"],
    category: "ai",
    url: `${GITHUB_BASE}/promptsister`,
  },
  {
    name: "emily_pantheon",
    title: "Emily Pantheon",
    description: "Emily AI 에이전트 패밀리. 다중 페르소나 AI 시스템 프로토타입.",
    stack: ["JavaScript", "Multi-Agent"],
    category: "ai",
    url: `${GITHUB_BASE}/emily_pantheon`,
  },
  {
    name: "AI_start_up_database",
    title: "AI Startup Database",
    description: "AI 스타트업 정보 데이터베이스. 글로벌 AI 스타트업 생태계 데이터 수집·분석.",
    stack: ["Python", "Database", "AI"],
    category: "ai",
    url: `${GITHUB_BASE}/AI_start_up_database`,
  },
  {
    name: "global_slang_dictionary",
    title: "Global Slang Dictionary",
    description: "글로벌 슬랭 사전. Python 기반 다국어·다문화 슬랭 데이터베이스와 검색 시스템.",
    stack: ["Python", "NLP", "Culture"],
    category: "global",
    url: `${GITHUB_BASE}/global_slang_dictionary`,
  },
  {
    name: "global-risk-war-room",
    title: "Global Risk War Room",
    description: "글로벌 리스크 워룸. Python 기반 지정학·문화 리스크 모니터링 및 시나리오 분석 도구.",
    stack: ["Python", "Risk Analytics"],
    category: "global",
    url: `${GITHUB_BASE}/global-risk-war-room`,
  },
  {
    name: "slang_dictionary",
    title: "Slang Dictionary",
    description: "슬랭 사전 웹앱. HTML 기반 슬랭 검색·학습 인터페이스.",
    stack: ["HTML", "Culture", "Dictionary"],
    category: "global",
    url: `${GITHUB_BASE}/slang_dictionary`,
  },
  {
    name: "traveleditor",
    title: "Travel Editor",
    description: "여행 편집기. TypeScript 기반 여행 콘텐츠 작성·편집 도구.",
    stack: ["TypeScript", "Editor", "Travel"],
    category: "global",
    url: `${GITHUB_BASE}/traveleditor`,
  },
  {
    name: "korean_war",
    title: "Korean War Simulation",
    description: "한국전쟁 브라우저 전략 시뮬레이션 (1945–1953). 역사적 사건을 기반으로 한 턴제 전략 게임.",
    stack: ["JavaScript", "Strategy", "History"],
    category: "games",
    url: `${GITHUB_BASE}/korean_war`,
  },
  {
    name: "halal_plane",
    title: "Halal Plane",
    description: "할랄 항공 여행 시뮬레이션. 문화·종교적 요구를 반영한 항공 여행 경험 게임.",
    stack: ["HTML", "Simulation", "Culture"],
    category: "games",
    url: `${GITHUB_BASE}/halal_plane`,
  },
  {
    name: "drunken_plane",
    title: "Drunken Plane",
    description: "유머 기반 항공 시뮬레이션. HTML/JavaScript 브라우저 게임.",
    stack: ["HTML", "Game"],
    category: "games",
    url: `${GITHUB_BASE}/drunken_plane`,
  },
  {
    name: "officewar",
    title: "Office War",
    description: "오피스 전쟁 시뮬레이션. JavaScript 기반 오피스 환경 전략 게임.",
    stack: ["JavaScript", "Strategy"],
    category: "games",
    url: `${GITHUB_BASE}/officewar`,
  },
  {
    name: "saigon_class",
    title: "Saigon Class",
    description: "사이공 클래스 — 베트남·동남아 문화 맥락의 인터랙티브 HTML 경험.",
    stack: ["HTML", "Culture", "History"],
    category: "games",
    url: `${GITHUB_BASE}/saigon_class`,
  },
  {
    name: "jumadeung_cinema",
    title: "Jumadeung Cinema",
    description: "주마등 시네마. JavaScript 기반 인터랙티브 영화·문화 체험 프로젝트.",
    stack: ["JavaScript", "Interactive"],
    category: "games",
    url: `${GITHUB_BASE}/jumadeung_cinema`,
  },
  {
    name: "AI-Teacher-Assistant",
    title: "AI Teacher Assistant",
    description: "AI 교사 어시스턴트. HTML 기반 교육자를 위한 AI 도구 프로토타입.",
    stack: ["HTML", "EdTech", "AI"],
    category: "edtech",
    url: `${GITHUB_BASE}/AI-Teacher-Assistant`,
  },
  {
    name: "ai-teacher-assistant-global-edition",
    title: "AI Teacher Assistant — Global Edition",
    description: "글로벌 에디션 AI 교사 어시스턴트. 다국어·다문화 교육 환경을 위한 확장 버전.",
    stack: ["HTML", "EdTech", "Global"],
    category: "edtech",
    url: `${GITHUB_BASE}/ai-teacher-assistant-global-edition`,
  },
  {
    name: "ai_tutorial",
    title: "AI Tutorial",
    description: "AI 학습 튜토리얼. JavaScript 기반 AI 개념 학습 인터랙티브 가이드.",
    stack: ["JavaScript", "Tutorial", "AI"],
    category: "edtech",
    url: `${GITHUB_BASE}/ai_tutorial`,
  },
  {
    name: "quartile_coaching",
    title: "Quartile Coaching",
    description: "Quartile 코칭 플랫폼. TypeScript 기반 데이터 기반 코칭·멘토링 도구.",
    stack: ["TypeScript", "Coaching", "Analytics"],
    category: "edtech",
    url: `${GITHUB_BASE}/quartile_coaching`,
  },
  {
    name: "readme_generator",
    title: "README Generator",
    description: "README 자동 생성기. Python으로 GitHub 리포지토리 README를 자동 작성.",
    stack: ["Python", "Automation", "GitHub"],
    category: "tools",
    url: `${GITHUB_BASE}/readme_generator`,
  },
  {
    name: "lazy_assignment",
    title: "Lazy Assignment",
    description: "과제 자동화 도구. Python 기반 반복 과제 처리 유틸리티.",
    stack: ["Python", "Automation"],
    category: "tools",
    url: `${GITHUB_BASE}/lazy_assignment`,
  },
];
