const GITHUB_BASE = "https://github.com/Benjamin5607";

const CATEGORIES = {
  ai: { label: "AI & Agentic Systems", icon: "🧠" },
  global: { label: "Global Culture & Risk", icon: "🌍" },
  games: { label: "Games & Simulations", icon: "🎮" },
  edtech: { label: "Education & Social Impact", icon: "📚" },
  tools: { label: "Developer Tools & Utilities", icon: "🛠️" },
};

const FEATURED_ORDER = [
  "zerro_ai_landing",
  "model_JekyllHyde",
  "ai_agent_emily",
  "ai_agent_mina",
  "emily_pantheon",
  "halal_plane",
];

function getFeaturedProjects() {
  return FEATURED_ORDER.map((name) => PROJECTS.find((p) => p.name === name)).filter(Boolean);
}

const PROJECTS = [
  {
    name: "model_JekyllHyde",
    title: "Jekyll & Hyde Dual-Persona LLM",
    description: "Jekyll and Hyde dual-persona LLM platform with install package. Self-hosted chat with Gemma 2 2B + LoRA, MCP, and domain packs. Release v1.2.1 install zip.",
    stack: ["Python", "Gemma 2", "LoRA", "MCP", "Self-hosted"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/model_JekyllHyde`,
  },
  {
    name: "Sereme_Hypatia",
    title: "Sereme Hypatia",
    description: "AI mind consulting. Full-stack TypeScript app (Vite, React 19, Express) with Google Gemini API.",
    stack: ["TypeScript", "React 19", "Vite", "Express", "Gemini API"],
    category: "ai",
    url: `${GITHUB_BASE}/Sereme_Hypatia`,
  },
  {
    name: "zerro_ai_landing",
    title: "Zerro AI OS",
    description: "Zerro AI OS — Tactical Swarm OS with Parallel Swarm Engine, Overseer agent, Supabase pgvector RAG, and MCP integration.",
    stack: ["Python", "Supabase", "MCP", "LangChain", "Parallel Swarm"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/zerro_ai_landing`,
    external: "https://zerroai.space",
  },
  {
    name: "space_manger",
    title: "Space Manager",
    description: "Real-time space data games: ISS supply mission and SpaceX tycoon sim. React 18 + Vite 6 + Leaflet, wheretheiss.at API.",
    stack: ["TypeScript", "React 18", "Vite 6", "Leaflet", "ISS API"],
    category: "games",
    url: `${GITHUB_BASE}/space_manger`,
  },
  {
    name: "country_janggi",
    title: "Country Janggi",
    description: "Country Janggi — 3D national-unit janggi with Hunyuan meshes and hanja piece labels. Vite, React 18, Three.js, R3F.",
    stack: ["TypeScript", "Three.js", "R3F", "Vite", "Python (assets)"],
    category: "games",
    url: `${GITHUB_BASE}/country_janggi`,
  },
  {
    name: "global_culture_risk_dashboard",
    title: "Global Culture Risk Dashboard",
    description: "Groq-driven scripts for culture/risk data generation and HTML dashboard visualization.",
    stack: ["HTML", "Python", "Groq API"],
    category: "global",
    url: `${GITHUB_BASE}/global_culture_risk_dashboard`,
  },
  {
    name: "traveleditor",
    title: "Emily Travel Editor",
    description: "Next.js 16 + React 19 + Tailwind 4 + Leaflet AI travel editor. Groq API, static export for GitHub Pages.",
    stack: ["TypeScript", "Next.js 16", "React 19", "Tailwind 4", "Groq", "Leaflet"],
    category: "global",
    url: `${GITHUB_BASE}/traveleditor`,
  },
  {
    name: "zerro_coder_test",
    title: "Zerro Coder Test",
    description: "Zerro autonomous agent QA smoke test project (Create React App).",
    stack: ["TypeScript", "Create React App"],
    category: "ai",
    url: `${GITHUB_BASE}/zerro_coder_test`,
  },
  {
    name: "ai_agent_emily",
    title: "Emily PM Agent",
    description: "Streamlit + Groq PM agent (KO/EN). Notion tasks, PM methodologies, SNS thread generation.",
    stack: ["Python", "Streamlit", "Groq API", "Notion API"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/ai_agent_emily`,
  },
  {
    name: "ai_agent_mina",
    title: "Lobster Chat Center (Mina)",
    description: "Streamlit multi-agent chat center. Groq + Gemini, Discord reporting, Notion/GitHub/Slack/Sheets tool hooks.",
    stack: ["Python", "Streamlit", "Groq", "Gemini", "Multi-Agent"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/ai_agent_mina`,
  },
  {
    name: "ai_agent_mina_automation",
    title: "Lobster Agent Automation",
    description: "LOBSTER AGENT automation: moviepy + gTTS, DuckDuckGo search, SNS/Notion/Slack content workflows.",
    stack: ["Python", "Streamlit", "moviepy", "gTTS", "Groq", "Gemini"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_mina_automation`,
  },
  {
    name: "AI_Red_Kernel_bot",
    title: "Red Kernel Bot",
    description: "Node.js + Groq RedKernel persona bot with Moltbook integration.",
    stack: ["JavaScript", "Node.js", "Groq API", "Moltbook"],
    category: "ai",
    url: `${GITHUB_BASE}/AI_Red_Kernel_bot`,
  },
  {
    name: "AI-Sports-Bot",
    title: "AI Sports Edge",
    description: "Groq + Tweepy sports AI bot. Google News/ESPN RSS RAG, Discord webhook workflow.",
    stack: ["Python", "Groq", "Tweepy", "RAG", "Discord Webhook"],
    category: "ai",
    url: `${GITHUB_BASE}/AI-Sports-Bot`,
  },
  {
    name: "promptsister",
    title: "PromptSister — Enterprise Co-Pilot",
    description: "Prompt generator. Role-based prompt builder (Team Manager, HRBP, Ops). Tailwind + marked.js.",
    stack: ["JavaScript", "HTML", "Tailwind CSS"],
    category: "ai",
    url: `${GITHUB_BASE}/promptsister`,
  },
  {
    name: "emily_pantheon",
    title: "Emily's AI Pantheon",
    description: "Flutter Web AI Pantheon: tarot, feng shui, saju experiences.",
    stack: ["Dart", "Flutter Web"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/emily_pantheon`,
    external: "https://benjamin5607.github.io/emily_pantheon/",
  },
  {
    name: "AI_start_up_database",
    title: "AI Startup Database",
    description: "Groq + Notion Client startup signal pipeline. Notion DB sync, optional Ghost CMS integration.",
    stack: ["Python", "Groq", "Notion API", "Ghost CMS"],
    category: "ai",
    url: `${GITHUB_BASE}/AI_start_up_database`,
  },
  {
    name: "global_slang_dictionary",
    title: "Global Slang Dictionary",
    description: "Multilingual slang research DB (14 langs). Crawl + LLM semantic analysis, Google Sheets pipeline.",
    stack: ["Python", "LLM", "BeautifulSoup", "Google Sheets"],
    category: "global",
    url: `${GITHUB_BASE}/global_slang_dictionary`,
  },
  {
    name: "global-risk-war-room",
    title: "Global Risk Radar v3.0",
    description: "Streamlit + Groq global risk control tower. Model picker, scan scope sidebar.",
    stack: ["Python", "Streamlit", "Groq", "Pandas", "NumPy"],
    category: "global",
    url: `${GITHUB_BASE}/global-risk-war-room`,
  },
  {
    name: "slang_dictionary",
    title: "Slang Dictionary Web",
    description: "Flask + Groq + BeautifulSoup slang dictionary. HTML front-end, Flutter pubspec included.",
    stack: ["Python", "Flask", "Groq", "HTML", "Flutter"],
    category: "global",
    url: `${GITHUB_BASE}/slang_dictionary`,
  },
  {
    name: "korean_war",
    title: "Korean War Tactics",
    description: "Korean War browser strategy simulation 1945–1953. 30 scenarios, commander mode, grid tactics.",
    stack: ["JavaScript", "HTML", "CSS"],
    category: "games",
    url: `${GITHUB_BASE}/korean_war`,
  },
  {
    name: "halal_plane",
    title: "Halal Plane PWA",
    description: "PWA for Muslim travelers: halal restaurants/cafes/mosques, Amina AI (Groq), GPS, world map.",
    stack: ["HTML", "JavaScript", "PWA", "Groq", "Leaflet"],
    category: "games",
    featured: true,
    url: `${GITHUB_BASE}/halal_plane`,
    external: "https://benjamin5607.github.io/halal_plane/",
  },
  {
    name: "drunken_plane",
    title: "Drunken Plane PWA",
    description: "Single-page PWA with Leaflet, dark/gold theme, manifest support.",
    stack: ["HTML", "JavaScript", "PWA", "Leaflet"],
    category: "games",
    url: `${GITHUB_BASE}/drunken_plane`,
  },
  {
    name: "officewar",
    title: "Office War",
    description: "12-stage office-themed browser shoot-'em-up. 9:00–21:00 crunch narrative, KO/EN, sprite art.",
    stack: ["JavaScript", "HTML", "CSS"],
    category: "games",
    url: `${GITHUB_BASE}/officewar`,
  },
  {
    name: "saigon_class",
    title: "Saigon Class",
    description: "Saigon Class single-page app with Vietnam red/yellow theme, mobile-oriented UI.",
    stack: ["HTML", "CSS"],
    category: "games",
    url: `${GITHUB_BASE}/saigon_class`,
  },
  {
    name: "jumadeung_cinema",
    title: "Jumadeung Cinema v5",
    description: "Interactive cinema v5: multi-act branching story, SVG assets.",
    stack: ["JavaScript", "HTML", "SVG"],
    category: "games",
    url: `${GITHUB_BASE}/jumadeung_cinema`,
  },
  {
    name: "AI-Teacher-Assistant",
    title: "K-Tutor Studio / AI Teacher Assistant",
    description: "Node server.mjs + Cloudflare Wrangler + Vercel. Tesseract OCR, PDF/Mammoth/XLSX, YouTube transcript API.",
    stack: ["HTML", "Node.js", "Tesseract OCR", "Cloudflare", "Vercel"],
    category: "edtech",
    url: `${GITHUB_BASE}/AI-Teacher-Assistant`,
  },
  {
    name: "ai-teacher-assistant-global-edition",
    title: "AI Teacher Assistant — Global Edition",
    description: "Global AI Teacher Assistant (English UI). Tesseract, pdf.js, mammoth, xlsx CDN stack.",
    stack: ["HTML", "JavaScript", "Tesseract", "pdf.js", "mammoth"],
    category: "edtech",
    url: `${GITHUB_BASE}/ai-teacher-assistant-global-edition`,
  },
  {
    name: "ai_tutorial",
    title: "AI Tutorial Masterclass",
    description: "AI Tutorial hub + course1–3 HTML modules, localized data.js TOC (kids → advanced tracks).",
    stack: ["JavaScript", "HTML"],
    category: "edtech",
    url: `${GITHUB_BASE}/ai_tutorial`,
  },
  {
    name: "quartile_coaching",
    title: "Quartile Coaching Dashboard",
    description: "React 19 + Vite 8 + Chart.js + Dexie SLA vs quota coaching dashboard. gh-pages deploy scripts.",
    stack: ["TypeScript", "React 19", "Vite 8", "Chart.js", "Dexie"],
    category: "edtech",
    url: `${GITHUB_BASE}/quartile_coaching`,
  },
  {
    name: "readme_generator",
    title: "README Generator & Code Review",
    description: "Groq Llama 3.1 README generator + code review. analyze.js CLI + Streamlit app.py.",
    stack: ["Python", "JavaScript", "Groq Llama 3.1", "Streamlit", "GitHub API"],
    category: "tools",
    url: `${GITHUB_BASE}/readme_generator`,
  },
  {
    name: "lazy_assignment",
    title: "Lazy Assignment (Vision Food Captioning)",
    description: "Groq llama-3.2-11b-vision food image captioning. structured_restaurant_data.json output.",
    stack: ["Python", "Groq Vision", "HTML"],
    category: "tools",
    url: `${GITHUB_BASE}/lazy_assignment`,
  },
];
