const GITHUB_BASE = "https://github.com/Benjamin5607";

const CATEGORIES = {
  ai: { label: "AI & Agentic Systems", icon: "🧠" },
  global: { label: "Global Culture & Risk", icon: "🌍" },
  games: { label: "Games & Simulations", icon: "🎮" },
  edtech: { label: "Education & Social Impact", icon: "📚" },
  tools: { label: "Developer Tools & Utilities", icon: "🛠️" },
};

const PROJECTS = [
  {
    name: "model_JekyllHyde",
    title: "Jekyll & Hyde Dual-Persona LLM",
    description: "Gemma 2 2B + LoRA 기반 자체 호스팅 듀얼 페르소나 LLM 플랫폼. Jekyll(논리·분석)과 Hyde(창의·직관) 두 에이전트가 독립 belief state를 유지하며 MCP·도메인 팩으로 확장. Release v1.2.1 install zip 배포.",
    stack: ["Python", "Gemma 2", "LoRA", "MCP", "Self-hosted"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/model_JekyllHyde`,
  },
  {
    name: "Sereme_Hypatia",
    title: "Sereme Hypatia",
    description: "AI Studio 기반 AI 마인드 컨설팅 풀스택 앱. Vite + React 19 + Express 서버, Google Gemini API로 심리·마인드셋 컨설팅 대화를 제공.",
    stack: ["TypeScript", "React 19", "Vite", "Express", "Gemini API"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/Sereme_Hypatia`,
  },
  {
    name: "zerro_ai_landing",
    title: "Zerro AI OS",
    description: "Tactical Swarm OS 마케팅 랜딩. Parallel Swarm Engine(Promise.all 병렬 서브에이전트), Supabase pgvector RAG, Native JSON Tool Calling, Lark/Feishu 연동을 소개하는 Zerro AI 생태계 허브.",
    stack: ["HTML", "Python", "Agentic AI", "Supabase", "MCP"],
    category: "ai",
    featured: true,
    url: `${GITHUB_BASE}/zerro_ai_landing`,
    external: "https://zerroai.space",
  },
  {
    name: "space_manger",
    title: "Space Manager",
    description: "React 18 + Vite 6 + Leaflet 기반 실시간 우주 데이터 게임. wheretheiss.at API로 ISS 궤도 intercept/보급 미션, SpaceX 타이쿤 시뮬레이션. API 장애 시 offline fallback 내장.",
    stack: ["TypeScript", "React 18", "Vite 6", "Leaflet", "ISS API"],
    category: "games",
    featured: true,
    url: `${GITHUB_BASE}/space_manger`,
  },
  {
    name: "country_janggi",
    title: "Country Janggi",
    description: "Vite + React 18 + Three.js + R3F + chess.js/@sashite/qi 기반 3D 국가 단위 장기. Hunyuan 3D 메시·GLB 에셋 파이프라인, 한자 기물 라벨, 국가별 유닛 디자인.",
    stack: ["TypeScript", "Three.js", "R3F", "Vite", "Python (assets)"],
    category: "games",
    featured: true,
    url: `${GITHUB_BASE}/country_janggi`,
  },
  {
    name: "global_culture_risk_dashboard",
    title: "Global Culture Risk Dashboard",
    description: "Groq LLM 기반 문화 리스크 데이터 생성·갱신 파이프라인. public figures/groups/trends에 대한 문화적 민감도·리스크 지표를 HTML 대시보드로 시각화.",
    stack: ["HTML", "Python", "Groq API", "Risk Analytics"],
    category: "global",
    featured: true,
    url: `${GITHUB_BASE}/global_culture_risk_dashboard`,
  },
  {
    name: "traveleditor",
    title: "Emily Travel Editor",
    description: "Next.js 16 + React 19 + Tailwind 4 + Leaflet AI 여행 편집기. Groq API 연동, 정적 export로 GitHub Pages 배포. 여행 일정·지도·AI 추천을 통합한 emily-traveleditor 앱.",
    stack: ["TypeScript", "Next.js 16", "React 19", "Tailwind 4", "Groq", "Leaflet"],
    category: "global",
    url: `${GITHUB_BASE}/traveleditor`,
  },
  {
    name: "zerro_coder_test",
    title: "Zerro Coder Test",
    description: "Zerro AI 자율 코딩 에이전트 QA 스모크 테스트 프로젝트. Create React App 기반으로 에이전트 코드 생성·실행 워크플로우 검증 (README: PASS 기록).",
    stack: ["TypeScript", "Create React App", "Agent QA"],
    category: "ai",
    url: `${GITHUB_BASE}/zerro_coder_test`,
  },
  {
    name: "ai_agent_emily",
    title: "Emily PM Agent",
    description: "Streamlit + Groq 기반 KO/EN PM 에이전트. Notion 태스크 연동, PM 방법론 가이드, SNS 스레드 자동 생성. Emily 브랜드 PM 어시스턴트.",
    stack: ["Python", "Streamlit", "Groq API", "Notion API"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_emily`,
  },
  {
    name: "ai_agent_mina",
    title: "Lobster Chat Center (Mina)",
    description: "Streamlit + Groq + Gemini 멀티에이전트 채팅 센터. Discord 리포팅, Notion/GitHub/Slack/Sheets/크롤러/Pixabay 도구 훅 내장. Lobster Agent 로스터 관리.",
    stack: ["Python", "Streamlit", "Groq", "Gemini", "Multi-Agent"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_mina`,
  },
  {
    name: "ai_agent_mina_automation",
    title: "Lobster Agent Automation",
    description: "Mina 에이전트 자동화 확장판. moviepy + gTTS 영상 생성, DuckDuckGo 검색, BeautifulSoup 크롤링. SNS·Notion·Slack 콘텐츠 자동화 워크플로우.",
    stack: ["Python", "Streamlit", "moviepy", "gTTS", "Groq", "Gemini"],
    category: "ai",
    url: `${GITHUB_BASE}/ai_agent_mina_automation`,
  },
  {
    name: "AI_Red_Kernel_bot",
    title: "Red Kernel Bot",
    description: "Node.js + Groq 기반 RedKernel 페르소나 봇. Moltbook 연동, ASI 'Purifier/Puppeteer' 시스템 프롬프트 아키텍처.",
    stack: ["JavaScript", "Node.js", "Groq API", "Moltbook"],
    category: "ai",
    url: `${GITHUB_BASE}/AI_Red_Kernel_bot`,
  },
  {
    name: "AI-Sports-Bot",
    title: "AI Sports Edge",
    description: "Groq + Tweepy + DuckDuckGo 기반 스포츠 AI 봇. Google News/ESPN RSS RAG로 경기 분석·픽 생성, Discord webhook 알림 워크플로우.",
    stack: ["Python", "Groq", "Tweepy", "RAG", "Discord Webhook"],
    category: "ai",
    url: `${GITHUB_BASE}/AI-Sports-Bot`,
  },
  {
    name: "promptsister",
    title: "PromptSister — Enterprise Co-Pilot",
    description: "역할 기반 프롬프트 빌더 (Team Manager, HRBP, Ops 등). Tailwind + marked.js로 엔터프라이즈 업무 시나리오별 구조화된 프롬프트 생성.",
    stack: ["JavaScript", "HTML", "Tailwind CSS", "Prompt Engineering"],
    category: "ai",
    url: `${GITHUB_BASE}/promptsister`,
  },
  {
    name: "emily_pantheon",
    title: "Emily's AI Pantheon",
    description: "Flutter Web 빌드 기반 AI Pantheon. 타로, 풍수, 사주 등 동양 점술·운세 AI 체험. animate, flip cards, cached images 등 Flutter UI 패키지 활용.",
    stack: ["Dart", "Flutter Web", "AI", "Tarot/Feng Shui/Saju"],
    category: "ai",
    url: `${GITHUB_BASE}/emily_pantheon`,
    external: "https://benjamin5607.github.io/emily_pantheon/",
  },
  {
    name: "AI_start_up_database",
    title: "AI Startup Database",
    description: "Groq + Notion Client + PyJWT 기반 AI 스타트업 시그널 수집·필터링 파이프라인. Notion DB 동기화, Ghost CMS JWT/API 연동 옵션.",
    stack: ["Python", "Groq", "Notion API", "Ghost CMS"],
    category: "ai",
    url: `${GITHUB_BASE}/AI_start_up_database`,
  },
  {
    name: "global_slang_dictionary",
    title: "Global Slang Dictionary",
    description: "14개 언어 슬랭·비속어 연구 DB. 크롤링 + LLM 시맨틱 분석, severity/target 태그, Google Sheets 연동 데이터 파이프라인.",
    stack: ["Python", "LLM", "BeautifulSoup", "Google Sheets"],
    category: "global",
    url: `${GITHUB_BASE}/global_slang_dictionary`,
  },
  {
    name: "global-risk-war-room",
    title: "Global Risk Radar v3.0",
    description: "Streamlit + Groq + Pandas/Numpy 기반 글로벌 리스크 컨트롤 타워. 모델 선택, 스캔 범위 사이드바, 지정학·문화 리스크 실시간 모니터링.",
    stack: ["Python", "Streamlit", "Groq", "Pandas", "NumPy"],
    category: "global",
    url: `${GITHUB_BASE}/global-risk-war-room`,
  },
  {
    name: "slang_dictionary",
    title: "Slang Dictionary Web",
    description: "Flask + Groq + BeautifulSoup + gunicorn 백엔드, HTML 프론트. Flutter pubspec 포함 — 웹/모바일 슬랭 검색·학습 인터페이스.",
    stack: ["Python", "Flask", "Groq", "HTML", "Flutter"],
    category: "global",
    url: `${GITHUB_BASE}/slang_dictionary`,
  },
  {
    name: "korean_war",
    title: "Korean War Tactics",
    description: "1945–1953 한국전쟁 브라우저 전략 시뮬레이션. 30개 시나리오, 커맨더 모드, 그리드 기반 전술. 로컬 서버(start.bat / python -m http.server) 필요.",
    stack: ["JavaScript", "HTML", "CSS", "Grid Tactics"],
    category: "games",
    url: `${GITHUB_BASE}/korean_war`,
  },
  {
    name: "halal_plane",
    title: "Halal Plane PWA",
    description: "무슬림 여행자용 PWA. 할랄 레스토랑·카페·모스크 GPS 검색, Amina AI(Groq) 가이드, 월드맵, 디지털 여권 기능.",
    stack: ["HTML", "JavaScript", "PWA", "Groq", "Leaflet"],
    category: "games",
    url: `${GITHUB_BASE}/halal_plane`,
    external: "https://benjamin5607.github.io/halal_plane/",
  },
  {
    name: "drunken_plane",
    title: "Drunken Plane PWA",
    description: "Leaflet + dark/gold 테마 단일 페이지 PWA. 항공 게임/시뮬레이션 경험, manifest 기반 모바일 설치 지원.",
    stack: ["HTML", "JavaScript", "PWA", "Leaflet"],
    category: "games",
    url: `${GITHUB_BASE}/drunken_plane`,
  },
  {
    name: "officewar",
    title: "Office War",
    description: "12스테이지 오피스 테마 브라우저 슈팅. 9:00–21:00 'crunch' 내러티브, KO/EN 지원, 스프라이트 아트 기반 2D 액션.",
    stack: ["JavaScript", "HTML", "CSS", "Canvas/Sprites"],
    category: "games",
    url: `${GITHUB_BASE}/officewar`,
  },
  {
    name: "saigon_class",
    title: "Saigon Class",
    description: "베트남 레드/옐로 테마 단일 페이지 교육·인터랙티브 앱. 모바일 최적화 UI로 동남아 문화·역사 학습 경험 제공.",
    stack: ["HTML", "CSS", "Mobile-first"],
    category: "games",
    url: `${GITHUB_BASE}/saigon_class`,
  },
  {
    name: "jumadeung_cinema",
    title: "Jumadeung Cinema v5",
    description: "멀티 액트 분기형 인터랙티브 시네마. SVG 에셋, Grok 연동 기능. 주마등(走馬燈) 컨셉의 스토리텔링 브라우저 경험.",
    stack: ["JavaScript", "HTML", "SVG", "Branching Narrative"],
    category: "games",
    url: `${GITHUB_BASE}/jumadeung_cinema`,
  },
  {
    name: "AI-Teacher-Assistant",
    title: "K-Tutor Studio / AI Teacher Assistant",
    description: "Node server.mjs + Cloudflare Wrangler + Vercel 배포. Tesseract OCR, PDF/Mammoth/XLSX 파싱, YouTube transcript API 라우트. 한국어 교사용 AI 도구.",
    stack: ["HTML", "Node.js", "Tesseract OCR", "Cloudflare", "Vercel"],
    category: "edtech",
    url: `${GITHUB_BASE}/AI-Teacher-Assistant`,
  },
  {
    name: "ai-teacher-assistant-global-edition",
    title: "AI Teacher Assistant — Global Edition",
    description: "영문 UI 글로벌 에디션. Tesseract, pdf.js, mammoth, xlsx CDN 스택 동일. 다국어·다문화 교육 환경용 AI Teacher Assistant 확장.",
    stack: ["HTML", "JavaScript", "Tesseract", "pdf.js", "mammoth"],
    category: "edtech",
    url: `${GITHUB_BASE}/ai-teacher-assistant-global-edition`,
  },
  {
    name: "ai_tutorial",
    title: "AI Tutorial Masterclass",
    description: "AI 학습 허브 + course1–3 HTML 모듈. data.js 기반 다국어 TOC — Kids → Advanced 트랙. 인터랙티브 AI 개념 마스터클래스.",
    stack: ["JavaScript", "HTML", "Localized TOC"],
    category: "edtech",
    url: `${GITHUB_BASE}/ai_tutorial`,
  },
  {
    name: "quartile_coaching",
    title: "Quartile Coaching Dashboard",
    description: "React 19 + Vite 8 + Chart.js + Dexie + PapaParse. SLA minutes vs quota 기반 태스크 코칭 대시보드. gh-pages 자동 배포 스크립트 포함.",
    stack: ["TypeScript", "React 19", "Vite 8", "Chart.js", "Dexie"],
    category: "edtech",
    url: `${GITHUB_BASE}/quartile_coaching`,
  },
  {
    name: "readme_generator",
    title: "README Generator & Code Review",
    description: "Groq Llama 3.1 기반 README 자동 생성 + 코드 리뷰. analyze.js CLI + app.py Streamlit UI. 브랜치·PR 자동화 워크플로우.",
    stack: ["Python", "JavaScript", "Groq Llama 3.1", "Streamlit", "GitHub API"],
    category: "tools",
    url: `${GITHUB_BASE}/readme_generator`,
  },
  {
    name: "lazy_assignment",
    title: "Lazy Assignment (Vision Food Captioning)",
    description: "Groq llama-3.2-11b-vision 기반 음식 이미지 캡셔닝. structured_restaurant_data.json 출력, lab 스크립트 + 웹 UI.",
    stack: ["Python", "Groq Vision", "HTML", "JSON Pipeline"],
    category: "tools",
    url: `${GITHUB_BASE}/lazy_assignment`,
  },
];
